name: bioptim_gui
description: This is a code generator for bioptim.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  window_manager: ^0.3.5
  file_picker: ^6.1.1
  path: ^1.8.3
  http: ^1.1.0
  provider: ^6.0.5
  fl_chart: ^0.65.0
  syncfusion_flutter_sliders: ^24.1.46

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/bioptim_tester.py
